# Default Configuration for 'SimonSays' - Eden.Campo

autoUpdate: true

useMySQL: false

host: host
port: port
database: db
user: username
password: pw

minimumPlayers: 3

enableDebug: false

configVersion: 1.0.6
firstStartup: yes