name: SimonSays
main: net.edencampo.simonsays.SimonSays
version: 1.0.3
author: Eden.Campo

commands:
  simonhelp:
      description: SimonSays Help Command
      usage: /<command>
  creategamearena:
      description: SimonSays Create Game Arena
      usage: /<command> <ArenaName> <RelatedArena>
  createspecarena:
      description: SimonSays Create Spectate Arena
      usage: /<command>
  deletearena:
      description: SimonSays Delete Arena
      usage: /<command> <ArenaName>
  simonjoin:
      description: SimonSays Join Arena
      usage: /<command> <ArenaName>
  simonleave:
      description: SimonSays Leave Arena
      usage: /<command>
      
      
permissions:
    SimonSays.*:
        description: Gives access everything related to SimonSays
        children:
            SimonSays.command.create: true
            SimonSays.command.delete: true
            SimonSays.command.join: true
            SimonSays.command.leave: true
            SimonSays.sign.create: true
            SimonSays.sign.destroy: true
            SimonSays.sign.use: true
            
    SimonSays.command.create:
        description: Gives the ability to create SimonArenas.
        default: op 
        
    SimonSays.command.delete:
        description: Gives the ability to delete SimonArenas.
        default: op 
        
    SimonSays.command.join:
        description: Gives the ability to join SimonArenas.
        default: true
        
    SimonSays.command.leave:
        description: Gives the ability to leave SimonArenas.
        default: true
        
    SimonSays.sign.create:
        description: Gives the ability to create SimonSigns.
        default: op
        
    SimonSays.sign.destroy:
        description: Gives the ability to destory SimonSigns.
        default: op
        
    SimonSays.sign.use:
        description: Gives the ability to use SimonSigns.
        default: true