name: SimonSays
main: net.edencampo.simonsays.SimonSays
version: 1.0.6
author: Eden.Campo

commands:
  simonsays:
      description: SimonSays's help command.
      usage: /<command>
  simonsays arena creategame:
      description: Creates a game arena linked with <RelatedArena> at your location.
      usage: /<command> <ArenaName> <RelatedArena>
  simonsays arena createspec:
      description: Creates a spectator arena linked with <RelatedArena> at your location.
      usage: /<command> <ArenaName>
  simonsays arena delete:
      description: Deletes <ArenaName>.
      usage: /<command> <ArenaName>
  simonsays arena list:
      description: Lists all existing arenas
      usage: /<command>
  simonsays join:
      description: Joins <ArenaName>,
      usage: /<command> <ArenaName>
  simonsays leave:
      description: Leaves your current arena.
      usage: /<command>
      
      
permissions:
    SimonSays.*:
        description: Gives access everything related to SimonSays
        children:
            SimonSays.command.create: true
            SimonSays.command.delete: true
            SimonSays.command.join: true
            SimonSays.command.leave: true
            SimonSays.sign.create: true
            SimonSays.sign.destroy: true
            SimonSays.sign.use: true
            
    SimonSays.command.create:
        description: Gives the ability to create SimonArenas.
        default: op 
        
    SimonSays.command.delete:
        description: Gives the ability to delete SimonArenas.
        default: op 
        
    SimonSays.command.join:
        description: Gives the ability to join SimonArenas.
        default: true
        
    SimonSays.command.leave:
        description: Gives the ability to leave SimonArenas.
        default: true
        
    SimonSays.sign.create:
        description: Gives the ability to create SimonSigns.
        default: op
        
    SimonSays.sign.destroy:
        description: Gives the ability to destory SimonSigns.
        default: op
        
    SimonSays.sign.use:
        description: Gives the ability to use SimonSigns.
        default: true