name: SimonSays
main: net.edencampo.simonsays.SimonSays
version: 1.0.2
author: Eden.Campo

commands:
  simonhelp:
      description: SimonSays Help Command
      usage: /<command>
  creategamearena:
      description: SimonSays Create Game Arena
      usage: /<command> <ArenaName> <RelatedArena>
  createspecarena:
      description: SimonSays Create Spectate Arena
      usage: /<command>
  deletearena:
      description: SimonSays Delete Arena
      usage: /<command> <ArenaName>
  simonjoin:
      description: SimonSays Join Arena
      usage: /<command> <ArenaName>
  simonleave:
      description: SimonSays Leave Arena
      usage: /<command>
      
      
permissions:
    SimonSays.*:
        description: Gives access everything related to SimonSays
        children:
            SimonSays.create: true
            SimonSays.delete: true
            SimonSays.join: true
            SimonSays.leave: true
            
    SimonSays.create:
        description: Gives the ability to create SimonArenas.
        default: op 
        
    SimonSays.delete:
        description: Gives the ability to delete SimonArenas.
        default: op 
        
    SimonSays.join:
        description: Gives the ability to join SimonArenas.
        default: true
        
    SimonSays.leave:
        description: Gives the ability to leave SimonArenas.
        default: true